### ISSUE TITLE
Unsafety in lib.rs

### ISSUE THREAD

**Issue by Stebalien** [Immington-Industries/rust-wlc#13]
``` rust
pub fn init(interface: WlcInterface) -> bool {
    unsafe {
        let args: Vec<*const libc::c_char> = env::args().into_iter()
            .map(|arg| arg.as_ptr() as *const libc::c_char ).collect();

        wlc_init(&interface, args.len() as i32, args.as_ptr() as *const *const libc::c_char)
    }
}
// ...
pub fn init_with_args(interface: WlcInterface, args: Vec<String>) -> bool {
    unsafe {
        wlc_init(&interface, args.len() as i32, args.as_ptr() as *const *const libc::c_char)
    }
}
```
1. The pointers to the arguments become invalid the second you drop the `String`s.
2. These strings are _not_ valid C strings (they aren't null terminated). Well, they are in this case but that's just coincidence and could break at any time.

``` rust
pub fn exec(bin: String, args: Vec<String>) {
    unsafe {
        let bin_c = CString::new(bin).unwrap().as_ptr() as *const libc::c_char;

        let argv: Vec<CString> = args.into_iter()
            .map(|arg| CString::new(arg).unwrap() ).collect();

        let args: Vec<*const libc::c_char> = argv.into_iter()
            .map(|arg: CString| { arg.as_ptr() as *const libc::c_char }).collect();

        wlc_exec(bin_c, args.as_ptr() as *const *const libc::c_char);
    }
}
```

Again, these pointers are invalid after you drop the CStrings themselves.

``` rust
pub fn pointer_to_string(pointer: *const libc::c_char) -> String {
    let slice = unsafe { ffi::CStr::from_ptr(pointer) };
    slice.to_string_lossy().into_owned()
}
```

This function really should be marked unsafe. `pointer` could point to anything.

**Comment by Timidger** [comment]
Fixed most issues with [this](https://github.com/Immington-Industries/rust-wlc/commit/051f7126f889989f5aeb71115b883444af0e7434) comment hash. 

I fixed the strings not being valid C strings (CString::new automatically makes it vaild) and changed pointer_to_string to be unsafe. For the string pointers that become invalid after we drop the strings, is there anything we can do other than by setting some static string to the passed in arguments (which would require an unsafe)? Because otherwise a string will always be dropped. I at first have done a copy, but I realise now that's even worse because it'll be dropped as soon as the function is done. Is there a better option or is a static the way to go?

**Comment by SnirkImmington** [comment]
On `pointer_to_string`

> This function really should be marked unsafe. `pointer` could point to anything.

This is a good point, when we were writing this we cared a little bit more about getting the types to match up than checking (we should get rid of the `.unwrap()`. 

I think the best way to handle this would be to return a `Result` if the conversion doesn't work. I'm not sure why this _must_ be `unsafe`, however. Can we return a `Result<&String>`?

**Comment by Timidger** [comment]
Well the problem with that is if the pointer points to invalid memory it'll be undefined behaviour (just because the code is safe calling it doesn't mean the pointer is valid)

**Comment by Stebalien** [comment]
The solution really depends on why wlc needs argv. Based on a read-through of the code, wlc appears to use argv to set the name of the program (`argv[0]`) and clear the rest of the arguments (after forking). So really, you should be passing in a raw pointer to the _real_ argv, not some copied version. However, it doesn't look like you _have_ to do this. It should be reasonable to just pass `null` for `argv` and `0` for `argc`.

**Comment by Stebalien** [comment]
Sorry, that only applies to `wlc_init`. `wlc_exec` uses the args as arguments to the command being executed. They only need to live to the end of the function call.

**Comment by Timidger** [comment]
Yeah I just did a quick read thorough my self and found the same thing for wlc init and that's probably that solution I'll implement. Thanks for your help.

**Comment by Timidger** [comment]
Fixed with  df1eac6

**Comment by Stebalien** [comment]
This isn't fixed. All calls to `CString::new(something).as_ptr()` are unsafe as the `CString` will be dropped immediately.
